### PR TITLE
Implement latest template in existing CBPPs

### PR DESCRIPTION
**Pull request by electrocucaracha**
The latest template versioned has not been used in the existing CBPPs. This change standardizes the existing CBPPs and fix some linting issues and removes/adds some word into the list.

### CODE REVIEW

**Review by taylor — CHANGES_REQUESTED** [review]
lgtm

**Comment by jeffsaelens** [comment]
lgtm

**Review by jeffsaelens — APPROVED** [review]
+1

**Review by lixuna — APPROVED** [review]
LGTM

**Review by agentpoyo — APPROVED** [review]
LGTM

**Review by taylor — APPROVED** [review]
+1 no changes needed

**Review by Smitholi67 — APPROVED** [review]
LGTM

**Pull request merged**
