### PR TITLE
Markdown link checking

### PR DESCRIPTION
**Pull request by iawells**
We had a couple of broken link incidents in another pull request.  This helps ensure we don't have that sort of thing again.

- [x] added linting github action on pull request, push
- [x] fixed a broken link
- [x] excluded check of a deliberately broken example link

### CODE REVIEW

**Comment by iawells** [comment]
This change is totally excellent and should be merged forthwith. Also, Ian is testing the github slack bot integration.

**Comment by taylor** [comment]
@iawells is there an example of this working you can link to in this PR?

**Comment by iawells** [comment]
Like on the original pull request?  https://github.com/iawells/cnf-wg/runs/1858632970?check_suite_focus=true - seems to have worked there, and it's spotted broken links in earlier revs - https://github.com/iawells/cnf-wg/actions?query=workflow%3A%22Check+Markdown+links%22

**Pull request merged**
