### PR TITLE
Create "Do not run containers with the privilege flag" best practice

### PR DESCRIPTION
**Pull request by electrocucaracha**
Closes Issue #67 
Discussion: Applying principle of the least privilege to CNFs  #28

### CODE REVIEW

**Review by taylor — APPROVED** [review]
lgtm

**Review by tomkivlin — APPROVED** [review]
lgtm

**Review by Smitholi67 — APPROVED** [review]
lgtm

**Review by Smitholi67 — APPROVED** [review]
lgtm

**Review by lixuna — APPROVED** [review]
lgtm

**Review by jeffsaelens — APPROVED** [review]
LGTM, next step maybe to write some of the BPs for the items listed in the notes/constraints/caveats?

**Review by nickolaev — APPROVED** [review]

**Pull request merged**
