### PR TITLE
add timeline for adding interested parties

### PR DESCRIPTION
**Pull request by xmulligan**

### CODE REVIEW

**Review by jeffsaelens — COMMENTED** [review]
LGTM

**Review by taylor — APPROVED** [review]
❌ ♻️ redacted approval.

**Review by taylor — CHANGES_REQUESTED** [review]
I thought this section was to communicate interest only and not about who is eligible to vote.  

It seems like anyone that is contributing would be eligible to vote and they may not be listed. Eg. Someone may be making lots of changes for instance via PRs, but not have their name (or company name) listed.

**Comment by iawells** [comment]
> I thought this section was to communicate interest only and not about who is eligible to vote.

Well, if that's the case, eligibility to vote is far closer to our critical path.

**Comment by iawells** [comment]
> > I thought this section was to communicate interest only and not about who is eligible to vote.
> 
> Well, if that's the case, eligibility to vote is far closer to our critical path.

Thinking about it, you can't ask everyone in a company to vote - so we need to create our electoral roll from a list of people.

**Review by iawells — APPROVED** [review]

**Review by jeffsaelens — APPROVED** [review]

**Review by rannyh — APPROVED** [review]
LGTM

**Review by electrocucaracha — APPROVED** [review]

**Review by rabi-abdel — APPROVED** [review]

**Pull request merged**
