### PR TITLE
Add life cycle management focus for CNF operators in README.md

### PR DESCRIPTION
**Pull request by rmerz**
For CNF operator, make the focus on life-cycle management much more explicit.

### CODE REVIEW

**Comment by rmerz** [comment]
I would like to put more focus on the overall life-cycle management

**Review by xmulligan — APPROVED** [review]

**Review by taylor — APPROVED** [review]
lgtm

**Review by CsatariGergely — APPROVED** [review]

**Review by rabi-abdel — APPROVED** [review]
great edition.

**Review by jeffsaelens — CHANGES_REQUESTED** [review]
made one small wording change

**Pull request merged**
