### PR TITLE
Moved best practices, user stories and use case folders under doc

### PR DESCRIPTION
**Pull request by ronit-nandwani**
Moved best practices, user stories and use case folders under doc
#247

### CODE REVIEW

**Comment by ronit-nandwani** [comment]
@electrocucaracha This is the PR for #247 issue. Please take a look when you get time and do let me know if all looks good.

**Comment by electrocucaracha** [comment]
@ronit-nandwani there ares [some issues](https://github.com/cncf/cnf-wg/actions/runs/5173926520/jobs/9331460156?pr=263#step:4:87) reported by the CI regarding the broken references, can you take a look and make sure they pass

**Comment by ronit-nandwani** [comment]
@electrocucaracha Pushed changes to fix broken references

**Review by electrocucaracha — APPROVED** [review]
/lgtm we can fix linting and spellchecker issues in subsequent PRs

**Review by tomkivlin — APPROVED** [review]
/lgtm

**Pull request merged**
