### PR TITLE
reword test plan

### PR DESCRIPTION
**Pull request by jeffsaelens**
Since we are avoiding compliance, and not fully fleshing out a test plan that provides the "how" of "what" should be tested. I think we should consider changing the title section to "Testing Considerations"

### CODE REVIEW

**Comment by jeffsaelens** [comment]
I think Guidance is a valid alternative to Considerations as well.

**Comment by iawells** [comment]
I still prefer 'Test objectives' - I think we're looking more at what you must prove rather than what you should consider in your testing ('you should consider how CPU intensive your tests are').

**Review by taylor — APPROVED** [review]

**Comment by taylor** [comment]
+1 test objectives

**Review by tliron — APPROVED** [review]

**Review by rannyh — APPROVED** [review]
LGTM

**Review by pgoyal01 — APPROVED** [review]

**Review by electrocucaracha — APPROVED** [review]

**Pull request merged**
