### PR TITLE
Add Glossary to Contributing.md

### PR DESCRIPTION
**Pull request by lixuna**
refs #89

### CODE REVIEW

**Comment by iawells** [comment]
Added issue #108, but that is a widespread problem and there's no point in fixing it in this one request.  LGTM

**Comment by iawells** [comment]
Actually, one question.  Some of these links are to tree/master, this one is to blob/master - is it correct?  I think it might link to the raw markdown and not the github-processed version.

**Review by taylor — APPROVED** [review]
lgmt

**Review by jeffsaelens — APPROVED** [review]
LGTM

**Review by xmulligan — APPROVED** [review]

**Review by electrocucaracha — APPROVED** [review]
/lgtm

**Pull request merged**
